In [21]:
import pandas as pd
from pathlib import Path
import numpy as np
import time
import requests

In [22]:
sightings_file = pd.read_csv('../Output/usa_sightings_df_.csv')
complete_file = pd.read_csv('../Output//city Data Complete.csv')

In [23]:
sightings_df = pd.DataFrame(sightings_file)
complete_df = pd.DataFrame(complete_file)

In [24]:
complete_df1=complete_df.drop(['Unnamed: 0'], axis = 1)

In [25]:
complete_df1  =complete_df1.rename(columns={'City': 'CITY'})
complete_df1

               CITY      Lat       Lng
0          Cranston  41.7798  -71.4373
1          Key West  24.5557  -81.7826
2     Oklahoma City  35.4676  -97.5164
3     Valley Stream  40.6643  -73.7085
4      Jacksonville  30.3322  -81.6556
...             ...      ...       ...
9108    Scottsville  36.7534  -86.1905
9109         Tehama  40.1332 -122.3011
9110          Wirtz  37.0765  -79.8895
9111      Lame Deer  45.6231 -106.6667
9112     Warr Acres  35.5226  -97.6189

[9113 rows x 3 columns]

In [26]:
#performing right join.
city_complete_df = pd.merge(sightings_df,  
                      complete_df1,  
                      on ='CITY', 
                      how ='right')

In [27]:
city_complete_df.head(20)

,SIGHTING_ID,OCCURRED_DATE,CITY,STATE,COUNTRY,SHAPE,SUMMARY,YEAR,CITYSTATE,Lat,Lng
0,1.0,2024-06-20,Cranston,RI,USA,Flash,My wife and I as well as our 2 children witnes...,2024.0,"Cranston, RI",41.7798,-71.4373
1,10490.0,2021-06-17,Cranston,RI,USA,Circle,At 11:50 am on june 17 2021 i seen a jet aircr...,2021.0,"Cranston, RI",41.7798,-71.4373
2,18342.0,2019-12-19,Cranston,RI,USA,Fireball,I was driving to work and i saw a ball of fire...,2019.0,"Cranston, RI",41.7798,-71.4373
3,21138.0,2019-07-15,Cranston,RI,USA,Other,"Object appears, moves, and disappears.",2019.0,"Cranston, RI",41.7798,-71.4373
4,21951.0,2019-05-25,Cranston,RI,USA,Circle,Circular looking UFO comes out of a chemtrail ...,2019.0,"Cranston, RI",41.7798,-71.4373
5,22817.0,2019-03-16,Cranston,RI,USA,Sphere,orange spheres moving side by side over rhode ...,2019.0,"Cranston, RI",41.7798,-71.4373
6,23160.0,2019-01-26,Cranston,RI,USA,Other,Heading towards work in a Uber i silently sat ...,2019.0,"Cranston, RI",41.7798,-71.4373
7,24829.0,2018-07-21,Cranston,RI,USA,Circle,Bright shimmering circular disk/orb seen and v...,2018.0,"Cranston, RI",41.7798,-71.4373
8,27952.0,2017-09-26,Cranston,RI,USA,Circle,red slow moving object in W sky. moved slowly....,2017.0,"Cranston, RI",41.7798,-71.4373
9,30367.0,2017-03-20,Cranston,RI,USA,Light,Two lights moving faster than an airplane. ((...,2017.0,"Cranston, RI",41.7798,-71.4373
10,34297.0,2016-07-03,Cranston,RI,USA,Oval,Four bright orange orbs drifted in the Eastern...,2016.0,"Cranston, RI",41.7798,-71.4373
11,34430.0,2016-06-25,Cranston,RI,USA,Cylinder,Orange fiery cylinder traveling slowly across ...,2016.0,"Cranston, RI",41.7798,-71.4373
12,34602.0,2016-06-11,Cranston,RI,USA,Orb,"Nine bright orange orbs drifted over Cranston,...",2016.0,"Cranston, RI",41.7798,-71.4373
13,36769.0,2015-12-24,Cranston,RI,USA,Oval,As soon as I exit the Walgreens on Broad. St M...,2015.0,"Cranston, RI",41.7798,-71.4373
14,2.0,2024-06-20,Key West,FL,USA,Light,Saw unexplainable lights slightly west of Nort...,2024.0,"Key West, FL",24.5557,-81.7826
15,2221.0,2023-08-28,Key West,FL,USA,Light,"Large, silent green light moved very slowly NW...",2023.0,"Key West, FL",24.5557,-81.7826
16,3097.0,2023-06-27,Key West,FL,USA,Orb,Orbs in key west,2023.0,"Key West, FL",24.5557,-81.7826
17,4043.0,2023-03-13,Key West,FL,USA,Orb,200ft to the left of the Edward B Knight Pier,2023.0,"Key West, FL",24.5557,-81.7826
18,13055.0,2020-10-06,Key West,FL,USA,Unknown,Shining orb flew in a zigzag pattern then disa...,2020.0,"Key West, FL",24.5557,-81.7826
19,15279.0,2020-05-11,Key West,FL,USA,Disk,5 circular crafts heading East in a staggered ...,2020.0,"Key West, FL",24.5557,-81.7826

In [28]:
# Convert SIGHTING_ID and YEAR to integers
city_complete_df['SIGHTING_ID'] = city_complete_df['SIGHTING_ID'].fillna(0).astype(int)
city_complete_df['YEAR'] = city_complete_df['YEAR'].fillna(0).astype(int)

In [29]:
# Remove NaN values from Lat and Lng columns
city_complete_df['Lat'] = city_complete_df['Lat'].fillna(0.0) 
city_complete_df['Lng'] = city_complete_df['Lng'].fillna(0.0)

In [30]:
# Drop rows where both Lat and Lng are NaN
city_complete_df = city_complete_df.dropna(subset=['Lat', 'Lng'])
city_complete_df = city_complete_df.dropna(subset=['CITYSTATE'])

In [31]:
# Round Lat / Lng for processing performance improvement in mapping
city_complete_df['Lat'] = city_complete_df['Lat'].round(2)
city_complete_df['Lng'] = city_complete_df['Lng'].round(2)

In [32]:
# Sort dataframe
city_complete_df = city_complete_df.sort_values(by=["OCCURRED_DATE"], ascending=False)

In [35]:
# Removing duplicates
city_complete_df = city_complete_df.drop_duplicates()

In [36]:
city_complete_df

,SIGHTING_ID,OCCURRED_DATE,CITY,STATE,COUNTRY,SHAPE,SUMMARY,YEAR,CITYSTATE,Lat,Lng
0,1,2024-06-20,Cranston,RI,USA,Flash,My wife and I as well as our 2 children witnes...,2024,"Cranston, RI",41.78,-71.44
14,2,2024-06-20,Key West,FL,USA,Light,Saw unexplainable lights slightly west of Nort...,2024,"Key West, FL",24.56,-81.78
47463,3,2024-06-20,Oklahoma City,OK,USA,Light,Erratically moving light at high altitude,2024,"Oklahoma City, OK",35.47,-97.52
94,4,2024-06-19,Valley Stream,NY,USA,Sphere,Sphere in the sky that glowed like an LED ligh...,2024,"Valley Stream, NY",40.66,-73.71
101,5,2024-06-19,Jacksonville,FL,USA,Triangle,Black triangle very low no noise,2024,"Jacksonville, FL",30.33,-81.66
...,...,...,...,...,...,...,...,...,...,...,...
34650,50221,2014-02-18,Tucson,AZ,USA,Orb,"REPORT FROM ATP PILOT: 3 orange orbs size, di...",2014,"Tucson, AZ",32.22,-110.93
9338,50219,2014-02-18,Houston,TX,USA,Disk,Silver disc on the right of me and then golden...,2014,"Houston, TX",29.76,-95.36
24507,50222,2014-02-18,Fallbrook,CA,USA,Orb,Orange orb with some intelligence.,2014,"Fallbrook, CA",33.38,-117.25
22963,50223,2014-02-18,Chandler,IN,USA,Other,Lighted object larger than a commercial a/c ho...,2014,"Chandler, IN",33.31,-111.84
63253,50226,2014-02-18,Lame Deer,MT,USA,Unknown,Orange lights slowly from south to north.,2014,"Lame Deer, MT",45.62,-106.67

In [37]:
city_complete_df.to_csv('../Output/City_latlng_merge.csv')