In [3]:
import pandas as pd
from pathlib import Path
from api_key import weather_api_key
import time
import requests

In [4]:
sightings_file = Path("Output/usa_sightings_df_.csv")
complete_file = Path("Output/city Data Complete.csv")

In [5]:
sightings_df = pd.read_csv(sightings_file)
complete_df = pd.read_csv(complete_file)

In [6]:
sightings_df

,SIGHTING_ID,OCCURRED_DATE,CITY,STATE,COUNTRY,SHAPE,SUMMARY,YEAR,CITYSTATE
0,1,2024-06-20,Cranston,RI,USA,Flash,My wife and I as well as our 2 children witnes...,2024.0,"Cranston, RI"
1,2,2024-06-20,Key West,FL,USA,Light,Saw unexplainable lights slightly west of Nort...,2024.0,"Key West, FL"
2,3,2024-06-20,Oklahoma City,OK,USA,Light,Erratically moving light at high altitude,2024.0,"Oklahoma City, OK"
3,4,2024-06-19,Valley Stream,NY,USA,Sphere,Sphere in the sky that glowed like an LED ligh...,2024.0,"Valley Stream, NY"
4,5,2024-06-19,Jacksonville,FL,USA,Triangle,Black triangle very low no noise,2024.0,"Jacksonville, FL"
...,...,...,...,...,...,...,...,...,...
50222,50223,2014-02-18,Chandler,IN,USA,Other,Lighted object larger than a commercial a/c ho...,2014.0,"Chandler, IN"
50223,50224,2014-02-18,Wentzville,MO,USA,Triangle,"Dark gray boomerang craft, no lights, gliding ...",2014.0,"Wentzville, MO"
50224,50225,2014-02-18,Mardela Springs,MD,USA,Light,One star-like light turned sharp and sped up t...,2014.0,"Mardela Springs, MD"
50225,50226,2014-02-18,Lame Deer,MT,USA,Unknown,Orange lights slowly from south to north.,2014.0,"Lame Deer, MT"
50226,50227,2014-02-18,Warr acres,OK,USA,Cone,White UFO in nw Oklahoma City.,2014.0,"Warr acres, OK"

In [7]:
complete_df1=complete_df.drop(['Unnamed: 0'], axis = 1)

In [8]:
complete_df1  =complete_df1.rename(columns={'City': 'CITY'})
complete_df1

               CITY      Lat       Lng
0          Cranston  41.7798  -71.4373
1          Key West  24.5557  -81.7826
2     Oklahoma City  35.4676  -97.5164
3     Valley Stream  40.6643  -73.7085
4      Jacksonville  30.3322  -81.6556
...             ...      ...       ...
9108    Scottsville  36.7534  -86.1905
9109         Tehama  40.1332 -122.3011
9110          Wirtz  37.0765  -79.8895
9111      Lame Deer  45.6231 -106.6667
9112     Warr Acres  35.5226  -97.6189

[9113 rows x 3 columns]

In [16]:
#performing right join.
city_complete_df = pd.merge(sightings_df,  
                      complete_df1,  
                      on ='CITY', 
                      how ='right')

In [18]:
city_complete_df.head(20)

,SIGHTING_ID,OCCURRED_DATE,CITY,STATE,COUNTRY,SHAPE,SUMMARY,YEAR,CITYSTATE,Lat,Lng
0,1.0,2024-06-20,Cranston,RI,USA,Flash,My wife and I as well as our 2 children witnes...,2024.0,"Cranston, RI",41.7798,-71.4373
1,10490.0,2021-06-17,Cranston,RI,USA,Circle,At 11:50 am on june 17 2021 i seen a jet aircr...,2021.0,"Cranston, RI",41.7798,-71.4373
2,18342.0,2019-12-19,Cranston,RI,USA,Fireball,I was driving to work and i saw a ball of fire...,2019.0,"Cranston, RI",41.7798,-71.4373
3,21138.0,2019-07-15,Cranston,RI,USA,Other,"Object appears, moves, and disappears.",2019.0,"Cranston, RI",41.7798,-71.4373
4,21951.0,2019-05-25,Cranston,RI,USA,Circle,Circular looking UFO comes out of a chemtrail ...,2019.0,"Cranston, RI",41.7798,-71.4373
5,22817.0,2019-03-16,Cranston,RI,USA,Sphere,orange spheres moving side by side over rhode ...,2019.0,"Cranston, RI",41.7798,-71.4373
6,23160.0,2019-01-26,Cranston,RI,USA,Other,Heading towards work in a Uber i silently sat ...,2019.0,"Cranston, RI",41.7798,-71.4373
7,24829.0,2018-07-21,Cranston,RI,USA,Circle,Bright shimmering circular disk/orb seen and v...,2018.0,"Cranston, RI",41.7798,-71.4373
8,27952.0,2017-09-26,Cranston,RI,USA,Circle,red slow moving object in W sky. moved slowly....,2017.0,"Cranston, RI",41.7798,-71.4373
9,30367.0,2017-03-20,Cranston,RI,USA,Light,Two lights moving faster than an airplane. ((...,2017.0,"Cranston, RI",41.7798,-71.4373
10,34297.0,2016-07-03,Cranston,RI,USA,Oval,Four bright orange orbs drifted in the Eastern...,2016.0,"Cranston, RI",41.7798,-71.4373
11,34430.0,2016-06-25,Cranston,RI,USA,Cylinder,Orange fiery cylinder traveling slowly across ...,2016.0,"Cranston, RI",41.7798,-71.4373
12,34602.0,2016-06-11,Cranston,RI,USA,Orb,"Nine bright orange orbs drifted over Cranston,...",2016.0,"Cranston, RI",41.7798,-71.4373
13,36769.0,2015-12-24,Cranston,RI,USA,Oval,As soon as I exit the Walgreens on Broad. St M...,2015.0,"Cranston, RI",41.7798,-71.4373
14,2.0,2024-06-20,Key West,FL,USA,Light,Saw unexplainable lights slightly west of Nort...,2024.0,"Key West, FL",24.5557,-81.7826
15,2221.0,2023-08-28,Key West,FL,USA,Light,"Large, silent green light moved very slowly NW...",2023.0,"Key West, FL",24.5557,-81.7826
16,3097.0,2023-06-27,Key West,FL,USA,Orb,Orbs in key west,2023.0,"Key West, FL",24.5557,-81.7826
17,4043.0,2023-03-13,Key West,FL,USA,Orb,200ft to the left of the Edward B Knight Pier,2023.0,"Key West, FL",24.5557,-81.7826
18,13055.0,2020-10-06,Key West,FL,USA,Unknown,Shining orb flew in a zigzag pattern then disa...,2020.0,"Key West, FL",24.5557,-81.7826
19,15279.0,2020-05-11,Key West,FL,USA,Disk,5 circular crafts heading East in a staggered ...,2020.0,"Key West, FL",24.5557,-81.7826

In [19]:
city_complete_df.to_csv('City_latlng_merge.csv')